"""empty message

Revision ID: 0ba51fa9c0bd
Revises: 0f5abc06ded3
Create Date: 2022-05-21 13:27:25.816915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba51fa9c0bd'
down_revision = '0f5abc06ded3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('city', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('profilePicture', sa.String(length=120), nullable=False))
    op.create_unique_constraint(None, 'user', ['profilePicture'])
    op.create_unique_constraint(None, 'user', ['fullname'])
    op.create_unique_constraint(None, 'user', ['city'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'profilePicture')
    op.drop_column('user', 'city')
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
