"""empty message

Revision ID: 124740130675
Revises: 4579bbf5b4f7
Create Date: 2022-05-21 15:35:15.298431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124740130675'
down_revision = '4579bbf5b4f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'date',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('trip', 'people',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('trip', 'cost',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Integer(),
               existing_nullable=False)
    op.drop_constraint('trip_destination_key', 'trip', type_='unique')
    op.drop_constraint('trip_people_key', 'trip', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trip_people_key', 'trip', ['people'])
    op.create_unique_constraint('trip_destination_key', 'trip', ['destination'])
    op.alter_column('trip', 'cost',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('trip', 'people',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    op.alter_column('trip', 'date',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###
