"""empty message

Revision ID: 199b62f502e2
Revises: 
Create Date: 2022-05-22 15:02:54.129502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '199b62f502e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('fullname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('city_of_residence', sa.String(length=120), nullable=False),
    sa.Column('profile_picture', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_of_trip_creator', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('date_of_the_trip', sa.Integer(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_of_trip_creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_of_social_network', sa.Integer(), nullable=True),
    sa.Column('trip_of_social_network', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_of_social_network'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_of_social_network'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_of_the_trip', sa.Integer(), nullable=True),
    sa.Column('trip_of_an_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creator_of_the_trip'], ['user.id'], ),
    sa.ForeignKeyConstraint(['trip_of_an_user'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed')
    op.drop_table('favorite')
    op.drop_table('trip')
    op.drop_table('user')
    op.drop_table('message')
    # ### end Alembic commands ###
