"""empty message

Revision ID: 380bc0c4e572
Revises: 5b454e8266ed
Create Date: 2022-05-21 15:24:57.956529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '380bc0c4e572'
down_revision = '5b454e8266ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trip', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.drop_column('trip', 'user_id')
    # ### end Alembic commands ###
