"""empty message

Revision ID: 38864e7ac0ac
Revises: d529fefd5f06
Create Date: 2022-05-22 14:08:02.454423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38864e7ac0ac'
down_revision = 'd529fefd5f06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('creator_of_the_trip', sa.Integer(), nullable=True))
    op.add_column('feed', sa.Column('trip_if_of_an_user', sa.Integer(), nullable=True))
    op.drop_constraint('feed_user_id_trip_fkey', 'feed', type_='foreignkey')
    op.create_foreign_key(None, 'feed', 'user', ['creator_of_the_trip'], ['id'])
    op.create_foreign_key(None, 'feed', 'trip', ['trip_if_of_an_user'], ['id'])
    op.drop_column('feed', 'user_id_trip')
    op.add_column('trip', sa.Column('user_id_of_trip_creator', sa.Integer(), nullable=True))
    op.add_column('trip', sa.Column('date_of_the_trip', sa.Integer(), nullable=False))
    op.drop_constraint('trip_user_id_fkey', 'trip', type_='foreignkey')
    op.create_foreign_key(None, 'trip', 'user', ['user_id_of_trip_creator'], ['id'])
    op.drop_column('trip', 'date')
    op.drop_column('trip', 'user_id')
    op.add_column('user', sa.Column('city_of_residence', sa.String(length=120), nullable=False))
    op.add_column('user', sa.Column('profile_picture', sa.String(length=120), nullable=False))
    op.drop_column('user', 'city')
    op.drop_column('user', 'profilePicture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilePicture', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('user', 'profile_picture')
    op.drop_column('user', 'city_of_residence')
    op.add_column('trip', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trip', sa.Column('date', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'trip', type_='foreignkey')
    op.create_foreign_key('trip_user_id_fkey', 'trip', 'user', ['user_id'], ['id'])
    op.drop_column('trip', 'date_of_the_trip')
    op.drop_column('trip', 'user_id_of_trip_creator')
    op.add_column('feed', sa.Column('user_id_trip', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feed', type_='foreignkey')
    op.drop_constraint(None, 'feed', type_='foreignkey')
    op.create_foreign_key('feed_user_id_trip_fkey', 'feed', 'trip', ['user_id_trip'], ['id'])
    op.drop_column('feed', 'trip_if_of_an_user')
    op.drop_column('feed', 'creator_of_the_trip')
    # ### end Alembic commands ###
