"""empty message

Revision ID: 4579bbf5b4f7
Revises: 380bc0c4e572
Create Date: 2022-05-21 15:30:51.318093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4579bbf5b4f7'
down_revision = '380bc0c4e572'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('acceptedTripList', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trip', 'acceptedTripList')
    # ### end Alembic commands ###
