"""empty message

Revision ID: 486ff374cbde
Revises: 19d574638d21
Create Date: 2022-06-10 10:11:51.943743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '486ff374cbde'
down_revision = '19d574638d21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'text',
               existing_type=sa.VARCHAR(length=220),
               type_=sa.String(length=280),
               existing_nullable=True)
    op.alter_column('user', 'description',
               existing_type=sa.VARCHAR(length=220),
               type_=sa.String(length=280),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'description',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=220),
               existing_nullable=True)
    op.alter_column('trip', 'text',
               existing_type=sa.String(length=280),
               type_=sa.VARCHAR(length=220),
               existing_nullable=True)
    # ### end Alembic commands ###
