"""empty message

Revision ID: 4ce9e4cb302e
Revises: 0ba51fa9c0bd
Create Date: 2022-05-21 13:31:34.919794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce9e4cb302e'
down_revision = '0ba51fa9c0bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.Column('people', sa.String(length=120), nullable=False),
    sa.Column('transport', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination'),
    sa.UniqueConstraint('people')
    )
    op.drop_constraint('user_city_key', 'user', type_='unique')
    op.drop_constraint('user_fullname_key', 'user', type_='unique')
    op.drop_constraint('user_profilePicture_key', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_profilePicture_key', 'user', ['profilePicture'])
    op.create_unique_constraint('user_fullname_key', 'user', ['fullname'])
    op.create_unique_constraint('user_city_key', 'user', ['city'])
    op.drop_table('trip')
    # ### end Alembic commands ###
