"""empty message

Revision ID: 4ed582925bec
Revises: f840d6522c8a
Create Date: 2022-05-25 17:07:58.717848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed582925bec'
down_revision = 'f840d6522c8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('start_of_the_trip', sa.Date(), nullable=False))
    op.add_column('trip', sa.Column('end_of_the_trip', sa.Date(), nullable=False))
    op.drop_column('trip', 'date_of_the_trip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trip', sa.Column('date_of_the_trip', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('trip', 'end_of_the_trip')
    op.drop_column('trip', 'start_of_the_trip')
    # ### end Alembic commands ###
