"""empty message

Revision ID: 5950de546c3b
Revises: e60f27fde2cc
Create Date: 2022-05-21 19:56:43.849877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5950de546c3b'
down_revision = 'e60f27fde2cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_trip', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id_trip'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed')
    # ### end Alembic commands ###
