"""empty message

Revision ID: 5b454e8266ed
Revises: c93fbb5651cc
Create Date: 2022-05-21 14:43:14.841184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b454e8266ed'
down_revision = 'c93fbb5651cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilePicture', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilePicture')
    # ### end Alembic commands ###
