"""empty message

Revision ID: 698430e969f0
Revises: ed5739249a34
Create Date: 2022-05-25 14:39:48.688795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698430e969f0'
down_revision = 'ed5739249a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('country', sa.String(length=120), nullable=True))
    op.drop_column('user', 'profile_picture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_picture', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_column('user', 'country')
    # ### end Alembic commands ###
