"""empty message

Revision ID: 6b2557664821
Revises: cb11bfaa65c0
Create Date: 2022-05-24 18:33:20.132429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b2557664821'
down_revision = 'cb11bfaa65c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'fullname',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'city_of_residence',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.alter_column('user', 'profile_picture',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'profile_picture',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'city_of_residence',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'fullname',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
