"""empty message

Revision ID: 761ef02b3b1b
Revises: 4ce9e4cb302e
Create Date: 2022-05-21 13:34:59.288208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761ef02b3b1b'
down_revision = '4ce9e4cb302e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('destination', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('people', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('transport', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('cost', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='trip_pkey'),
    sa.UniqueConstraint('destination', name='trip_destination_key'),
    sa.UniqueConstraint('people', name='trip_people_key')
    )
    # ### end Alembic commands ###
