"""empty message

Revision ID: 90eb5b45789c
Revises: 9b64b9bd00fa
Create Date: 2022-07-11 15:58:30.473002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90eb5b45789c'
down_revision = '9b64b9bd00fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match_trip', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('match_trip', 'confirmed')
    # ### end Alembic commands ###
