"""empty message

Revision ID: a8126df1d136
Revises: 38864e7ac0ac
Create Date: 2022-05-22 14:17:41.283084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8126df1d136'
down_revision = '38864e7ac0ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_of_social_network', sa.Integer(), nullable=True),
    sa.Column('trip_of_social_network', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_of_social_network'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_of_social_network'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('feed', sa.Column('trip_of_an_user', sa.Integer(), nullable=True))
    op.drop_constraint('feed_trip_if_of_an_user_fkey', 'feed', type_='foreignkey')
    op.create_foreign_key(None, 'feed', 'trip', ['trip_of_an_user'], ['id'])
    op.drop_column('feed', 'trip_if_of_an_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed', sa.Column('trip_if_of_an_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'feed', type_='foreignkey')
    op.create_foreign_key('feed_trip_if_of_an_user_fkey', 'feed', 'trip', ['trip_if_of_an_user'], ['id'])
    op.drop_column('feed', 'trip_of_an_user')
    op.drop_table('favorite')
    # ### end Alembic commands ###
