"""empty message

Revision ID: ba0643168c21
Revises: 199b62f502e2
Create Date: 2022-05-22 15:03:05.101161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0643168c21'
down_revision = '199b62f502e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('message_of_user', sa.Text(), nullable=True))
    op.alter_column('trip', 'date_of_the_trip',
               existing_type=sa.INTEGER(),
               type_=sa.Date(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip', 'date_of_the_trip',
               existing_type=sa.Date(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('message', 'message_of_user')
    # ### end Alembic commands ###
