"""empty message

Revision ID: c93fbb5651cc
Revises: f79bde052d9e
Create Date: 2022-05-21 14:42:52.255381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c93fbb5651cc'
down_revision = 'f79bde052d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profilePicture')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profilePicture', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
