"""empty message

Revision ID: dd3376cd71e0
Revises: 
Create Date: 2022-05-25 18:22:20.606840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd3376cd71e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faq', sa.Text(), nullable=False),
    sa.Column('recomendations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=True),
    sa.Column('firstname', sa.String(length=120), nullable=True),
    sa.Column('lastname', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('city_of_residence', sa.String(length=120), nullable=True),
    sa.Column('profile_picture', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id_of_trip_creator', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('start_of_the_trip', sa.Date(), nullable=False),
    sa.Column('end_of_the_trip', sa.Date(), nullable=False),
    sa.Column('people', sa.Integer(), nullable=False),
    sa.Column('transport', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('destination_picture', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['user_id_of_trip_creator'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('rejected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_trip')
    op.drop_table('trip')
    op.drop_table('user')
    op.drop_table('help')
    # ### end Alembic commands ###
