"""empty message

Revision ID: e5f29ae0d021
Revises: 13f01b665e9b
Create Date: 2022-05-24 18:06:12.399724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5f29ae0d021'
down_revision = '13f01b665e9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('help',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faq', sa.Text(), nullable=False),
    sa.Column('recomendations', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('help')
    # ### end Alembic commands ###
