"""empty message

Revision ID: ed5739249a34
Revises: 5ba2ea0c85ea
Create Date: 2022-05-25 14:30:45.800005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed5739249a34'
down_revision = '5ba2ea0c85ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'description')
    # ### end Alembic commands ###
