"""empty message

Revision ID: f79bde052d9e
Revises: 761ef02b3b1b
Create Date: 2022-05-21 13:36:05.122065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f79bde052d9e'
down_revision = '761ef02b3b1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('date', sa.String(length=120), nullable=False),
    sa.Column('people', sa.String(length=120), nullable=False),
    sa.Column('transport', sa.String(length=120), nullable=False),
    sa.Column('cost', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('destination'),
    sa.UniqueConstraint('people')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip')
    # ### end Alembic commands ###
